version: "3.6"

networks:
  internal:
    driver: bridge

volumes:
  postgre_vol:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./docker/postgres_data

  nest_vol:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./backend

  react_vol:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./frontend

services:

  postgres:
    container_name: postgres
    image: postgres
    volumes:
    - postgre_vol:/var/lib/postgresql/data/
    environment:
      DATABASE_URL: $DATABASE_URL
      POSTGRES_DB: $POSTGRES_DB
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    networks:
    - internal
    restart: unless-stopped
    #init: true

  nest_js:
    container_name: nest_js
    build: ./docker/backend
    environment:
      DATABASE_URL: $DATABASE_URL
      POSTGRES_HOST: $POSTGRES_HOST
      POSTGRES_DB: $POSTGRES_DB
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      PORT: $PORT
      CHAT_PORT: $CHAT_PORT
      GAME_PORT: $GAME_PORT
      WEBSOCKET_PORT: $WEBSOCKET_PORT
      GOOGLE_CLIENT_ID: $GOOGLE_CLIENT_ID
      GOOGLE_CLIENT_SECRET: $GOOGLE_CLIENT_SECRET
      GOOGLE_REDIRECT_URI: $GOOGLE_REDIRECT_URI
      GOOGLE_REFRESH_TOKEN: $GOOGLE_REFRESH_TOKEN
      REACT_APP_ID: $REACT_APP_ID
      REACT_APP_SECRET: $REACT_APP_SECRET
      REACT_APP_IP: $REACT_APP_IP
      CALLBACK_URL: $CALLBACK_URL
      JWT_SECRET: $JWT_SECRET
      COOKIE_SECRET: $COOKIE_SECRET
      BREVO_API_KEY: $BREVO_API_KEY
    ports:
      - "5555:5555"
      - ${WEBSOCKET_PORT}:${WEBSOCKET_PORT}
      - ${PORT}:${PORT}
      - ${CHAT_PORT}:${CHAT_PORT}
      - ${GAME_PORT}:${GAME_PORT}
    volumes:
    - nest_vol:/nest/
    - react_vol:/react/
    - /nest/node_modules
    - /react/node_modules
    networks:
    - internal
    depends_on:
    - postgres
    restart: unless-stopped
    #init: true
  
  react_js:
    container_name: react_js
    build: ./docker/frontend
    environment:
      REACT_PORT: $REACT_PORT
      REACT_APP_ID: $REACT_APP_ID
      REACT_APP_SECRET: $REACT_APP_SECRET
      CALLBACK_URL: $CALLBACK_URL
      REACT_APP_IP: $REACT_APP_IP
    ports:
      - ${REACT_PORT}:${REACT_PORT}
    networks:
    - internal
    volumes:
    - nest_vol:/nest/
    - react_vol:/react/
    - /nest/node_modules
    - /react/node_modules
    depends_on:
    - nest_js
    restart: unless-stopped
    #init: true