version: "3.6"

networks:
  internal:
    driver: bridge

volumes:
  postgre_vol:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./postgres_data

  nest_vol:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ../backend

  react_vol:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ../frontend

services:

  postgres:
    container_name: postgres
    image: postgres
    volumes:
    - postgre_vol:/var/lib/postgresql/data/
    environment:
      DATABASE_URL: $DATABASE_URL
      POSTGRES_DB: $POSTGRES_DB
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    networks:
    - internal
    restart: unless-stopped

  nest_js:
    container_name: nest_js
    build: ./backend
    environment:
      DATABASE_URL: $DATABASE_URL
      POSTGRES_HOST: $POSTGRES_HOST
      POSTGRES_DB: $POSTGRES_DB
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      PORT: $PORT
      CHAT_PORT: $CHAT_PORT
      GAME_PORT: $GAME_PORT
      WEBSOCKET_PORT: $WEBSOCKET_PORT
      REACT_APP_ID: $REACT_APP_ID
      REACT_APP_SECRET: $REACT_APP_SECRET
      CALLBACK_URL: $CALLBACK_URL
      JWT_SECRET: $JWT_SECRET
      JWT_EXPIRES_IN: $JWT_EXPIRES_IN
    ports:
      - "5555:5555"
      - ${WEBSOCKET_PORT}:${WEBSOCKET_PORT}
      - ${PORT}:${PORT}
      - ${CHAT_PORT}:${CHAT_PORT}
      - ${GAME_PORT}:${GAME_PORT}
    volumes:
    - nest_vol:/nest/
    - react_vol:/react/
    networks:
    - internal
    depends_on:
    - postgres
    restart: unless-stopped
  
  react_js:
    container_name: react_js
    build: ./frontend
    environment:
      REACT_PORT: $REACT_PORT
      REACT_APP_ID: $REACT_APP_ID
      REACT_APP_SECRET: $REACT_APP_SECRET
      CALLBACK_URL: $CALLBACK_URL
    ports:
    - ${REACT_PORT}:${REACT_PORT}
    networks:
    - internal
    volumes:
    - nest_vol:/nest/
    - react_vol:/react/
    depends_on:
    - nest_js
    restart: unless-stopped
